spring.application.name=flight-booking-backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/FlightBookingSystem
spring.datasource.username=postgres
spring.datasource.password=divya

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=flight_booking_system

# Server
server.port=8080

# Spring AI Ollama Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=tinyllama
